package com.example.myapplication.Models;

import java.util.HashMap;

public class User extends FirebaseUserModel{
    private String name;
    private String email;
    private String phone;
    private TravelDoc passport;

    private HashMap<String, Trips> UserTrips = new HashMap<>();

    // all args constructor
    public User(String userKey, String name, String email, String phone, TravelDoc passport) {
        super(userKey);
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.passport = passport;
    }
    // convenience constructor - sign in with google
    public User(String id, String name, String email) {
        super(id);
        this.name = name;
        this.email = email;
    }
    // convenience constructor - register
    public User(String name, String email) {
        super(null); // will be generated by firebase
        this.name = name;
        this.email = email;
    }

    public User(String uid, String displayName, String email, String phoneNumber) {
        this.name = name;
        this.email = email;
        this.phone = phone;
    }


    public TravelDoc getPassport() {
        return passport;
    }

    public void setPassport(TravelDoc passport) {
        this.passport = passport;
    }

    // no args constructor (firebase)
    public User() {}


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getImage() {
        return phone;
    }

    public void setImage(String image) {
        this.phone = image;
    }

    public String getPhone() {
        return phone;
    }

    public User setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    public HashMap<String, Trips> getUserTrips() {
        return UserTrips;
    }

    public User setUserTrips(HashMap<String, Trips> userTrips) {
        UserTrips = userTrips;
        return this;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", passport=" + passport +
                ", UserTrips=" + UserTrips +
                '}';
    }
}
